kind: pipeline

steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:9.0
  environment:
    nuget_api_key:
      from_secret: nuget_api_key
  commands:
  - dotnet nuget add source https://repository.decryptology.net/repository/Nuget/ -n decryptology.net
  - dotnet pack
  - dotnet nuget push /drone/src/SimpleDatabase/bin/Debug/SimpleDatabase.2.0.3.nupkg --api-key $nuget_api_key --source https://repository.decryptology.net/repository/Nuget/index.json

